version: '3.9'

services:
# Servicio para PostgreSQL
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:14
    container_name: medallero_postgres_db
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
  # Service for Neo4j
  neo4j:
    image: neo4j:latest
    container_name: medallero_neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/admin123 # You can change the credentials
    ports:
      - "7474:7474"
      - "7687:7687"

  # Service for Spring Boot
  springboot:
    build:
      context: . # Path to your Spring Boot application code
      dockerfile: Dockerfile
    container_name: medallero_springboot
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - neo4j

  # Service for PgAdmin
  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: medallero_pg_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
  neo4j:
    image: neo4j:4.3.5
    container_name: eventos
    restart: always
    environment:
      NEO4J_AUTH: neo4j/neo4j-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins