spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j-neo4j
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: rlozano@fi.uba.ar #uso mi mail como servidor smtp
    password: wtatipasgkbahdfq
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351