spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: rlozano@fi.uba.ar #uso mi mail como servidor smtp
    password: wtatipasgkbahdfq
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351